Menu/config/routes.rb
Rails.application.routes.draw do
  get 'cliente/index'

  get 'proveedor/index'

  get 'venta/index'

  get 'productos/index'

  get 'welcome/index'
  get 'menu/producto'

  root 'welcome#index'

end

Menu/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Menu/app/controllers/cliente_controller.rb
class ClienteController < ApplicationController
  def index
  end
end

Menu/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index
  end
end

Menu/app/controllers/proveedor_controller.rb
class ProveedorController < ApplicationController
  def index
  end
end

Menu/app/controllers/venta_controller.rb
class VentaController < ApplicationController
  def index
  end
end

Menu/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Menu/app/helpers/application_helper.rb
module ApplicationHelper
end

Menu/app/helpers/cliente_helper.rb
module ClienteHelper
end

Menu/app/helpers/productos_helper.rb
module ProductosHelper
end

Menu/app/helpers/proveedor_helper.rb
module ProveedorHelper
end

Menu/app/helpers/venta_helper.rb
module VentaHelper
end

Menu/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Menu/app/views/cliente/index.html.erb
<h1>Clientes</h1>
<p>Apartado de clientes</p>

Menu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menu</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,100,700,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav class="be-red white">
    <ul class="no-list row center-xs middle-xs">
      <li class="col-md">
        <h1 class="no-margin" id="menu">MENÚ</h1>
      </li>
      <li class="col-md">
          <%=link_to "Inicio", root_path %>
      </li>
      <li class="col-md">
        <%=link_to "Producto", productos_index_path%>
      </li>
      <li class="col-md">
        <%=link_to "Venta", venta_index_path%>
      </li>
      <li class="col-md">
        <%=link_to "Proveedor", proveedor_index_path%>
      </li>
      <li class="col-md">
        <%=link_to "Clientes", cliente_index_path %>
      </li>
    </ul>
  </nav>
</header>

<%= yield %>

</body>
</html>

Menu/app/views/productos/index.html.erb
<h1>Productos</h1>
<p>Apartado de productos</p>

Menu/app/views/proveedor/index.html.erb
<h1>Proveedor</h1>
<p>Apartado de proveedores</p>

Menu/app/views/venta/index.html.erb
<h1>Venta</h1>
<p>Apartado de ventas</p>

Menu/app/views/welcome/index.html.erb
<h1>Bienvenido a este menu</h1>